apiVersion: v1
kind: Service
metadata:
    name: svc-fiap-autenticacao-nodeport
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 8080
          nodePort: 31305
    selector:
        app: fiap-autenticacao