apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-contracts-deployment
  labels:
    app: fiap-contracts
    instance: fiap-contracts-app
  annotations:
    description: "Este é a instância do microsserviço contracts da minha aplicação."
    autor: Grupo 31
spec:
  replicas: 2  # Número de réplicas do contracts
  selector:
    matchLabels:
      app: fiap-contracts
  template:
    metadata:
      labels:
        app: fiap-contracts
    spec:
      containers:
        - name: fiap-contracts
          image: letticialuize/hackathonfiap-contracts:1.0
          ports:
            - containerPort: 3003
          
          envFrom:
            - configMapRef:
                name: fiap-configmap    
          volumeMounts:
            - name: shared
              mountPath: /app/data  # Local onde o volume será montado
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: fiap-mssql-pvc  # PVC para persistência dos dados
