apiVersion: v1
kind: Service
metadata:
    name: svc-fiap-contracts-nodeport
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 3003
          nodePort: 31303
    selector:
        app: fiap-contracts