apiVersion: v1
kind: Service
metadata:
    name: svc-fiap-gestaoconsultas-nodeport
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 3004
          nodePort: 31304
    selector:
        app: fiap-gestaoconsultas