name: HackathonHealthMed

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
    
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
      
    - name: List files
      run: ls -R
      
    - name: Restore dependencies
      run: dotnet restore HackathonFIAP/HackathonHealthMed.sln
      
    - name: Build
      run: dotnet build HackathonFIAP/HackathonHealthMed.sln --no-restore
      
    - name: Test
      run: dotnet test HackathonFIAP/HackathonHealthMed.sln --no-build --verbosity normal
